baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Kaldi"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/og-image.jpg", "https://i.etsystatic.com/19670708/r/il/be0d2f/3759811548/il_1588xN.3759811548_cgja.jpg"]